// react-slh/src/pages/Login.jsx
import React, { useState, useEffect } from "react";
import axios from 'axios';
import { Typography, TextField, Box } from '@mui/material';
import logo from '../assets/Logo.png';
import Button from '@mui/material/Button';
import { useNavigate } from 'react-router-dom';
import CryptoJS from 'crypto-js';
import { useTheme, useMediaQuery } from '@mui/material';
import Modal from '../components/Modal';

function Login() {
    const URL = "http://localhost:3001/apis/admin/login";
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [error, setError] = useState('');
    const navigate = useNavigate();
    const theme = useTheme();
    const isMobile = useMediaQuery(theme.breakpoints.down('sm'));
    const isTablet = useMediaQuery(theme.breakpoints.between('sm', 'md'));
    const [openModal, setOpenModal] = useState(false);
    const [modalMessage, setModalMessage] = useState('');

    useEffect(() => {
        // 로그인 상태인 경우 관리자 페이지로 리디렉션
        if (localStorage.getItem('isLoggedIn') === 'true') {
            navigate('/slhadmin');
        }
        // 컴포넌트 마운트 시 기존 타이머 제거
        clearTimeout(localStorage.getItem('loginTimeout'));
        // 컴포넌트 언마운트 시 타이머 제거
        return () => {
            clearTimeout(localStorage.getItem('loginTimeout'));
        };
    }, [navigate]);

    const handleLogin = async (e) => {
        e.preventDefault();
        if (!username && !password) {
          setModalMessage('아이디와 비밀번호를 입력해주세요.');
          setOpenModal(true);
          return;
        } else if (!username) {
            setModalMessage('아이디를 입력해주세요.');
            setOpenModal(true);
            return;
        } else if (!password) {
            setModalMessage('비밀번호를 입력해주세요.');
            setOpenModal(true);
            return;
        }
        try {
            const encryptedPassword = CryptoJS.SHA256(password).toString();

            const response = await axios.get(URL, {
              params: { id: username, pw: encryptedPassword },
              withCredentials: true
            });
            // console.log(response);

            if (response.status === 200) {
                const { ADMIN_ID, ADMIN_NM } = response.data.dataInfo;
                localStorage.setItem('isLoggedIn', 'true');
                localStorage.setItem('adminId', ADMIN_ID);
                localStorage.setItem('adminName', ADMIN_NM);

                const timer = setTimeout(() => {
                  localStorage.removeItem('isLoggedIn', 'false');
                }, 10000); // 10초 후 로그인 상태 제거

                localStorage.setItem('loginTimeout', timer);

                navigate('/slhadmin');
            } else {
                setError('로그인에 실패했습니다. 아이디와 비밀번호를 확인해주세요.');
            }
        } catch (err) {
            setError('로그인 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.');
        }
    };

    const handleCloseModal = () => {
        setOpenModal(false);
    };

    return(
      <Box sx={{
        display: "flex",
        justifyContent: "center",
        width: "100%",
        margin: { xs: "40px auto", sm: "60px auto", md: "80px auto" },
        padding: { xs: "0 20px", sm: "0 40px", md: 0 },
      }}>
        <Box sx={{
          display: "flex",
          flexDirection: { xs: "column", md: "row" },
          justifyContent: "center",
          alignItems: "center",
          width: "100%",
          maxWidth: "1200px",
        }}>
          {/* 왼쪽 div */}
          <Box sx={{
            width: { xs: "100%", md: "500px" },
            marginTop: { xs: "20px", md: "100px" },
            textAlign: { xs: "center", md: "left" },
          }}>
            <img src={logo} alt="logo" 
            style={{
              width: isMobile ? "200px" : isTablet ? "250px" : "350px",
              height: "auto",
              cursor: "pointer",
            }} 
            onClick={() => navigate('/')} />
          </Box>

          {/* 오른쪽 div (로그인 영역) */}
          <Box sx={{
            width: { xs: "100%", md: "400px" },
            display: "flex",
            flexDirection: "column",
            gap: "10px",
            marginTop: { xs: "20px", md: "200px" },
          }}>
            <TextField
              label="아이디"
              placeholder="아이디를 입력해주세요"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              fullWidth
            />
            <TextField
              label="비밀번호"
              placeholder="비밀번호를 입력해주세요"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              fullWidth
            />
            <Button
              variant="contained"
              onClick={handleLogin}
              style={{
                width: '100%',
                height: '56px',
                backgroundColor: 'black',
                color: 'white',
                marginTop: '10px',
                marginBottom: '10px',
                fontSize: '18px',
              }}
            >
              로그인
            </Button>
            {error && <Typography color="error">{error}</Typography>}
            <Box sx={{ display: "flex", justifyContent: "space-between" }}>
              <Typography onClick={() => navigate('/signup')} variant="body2" style={{cursor: "pointer"}}>회원가입</Typography>
              <Typography variant="body2" style={{color:"#808080"}}>ID찾기</Typography>
              <Typography variant="body2" style={{color:"#808080"}}>P/W 찾기</Typography>
            </Box>
          </Box>
        </Box>
        <Modal open={openModal} onClose={handleCloseModal} message={modalMessage} />
      </Box>
    )
}

export default Login;

// vue3-slh/src/views/Login.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import axios from 'axios'
import CryptoJS from 'crypto-js'
import { useDisplay } from 'vuetify'
import logo from '../assets/Logo.png'

const router = useRouter()
const route = useRoute()
const URL = "http://localhost:3001/apis/admin/login"
const username = ref('')
const password = ref('')
const error = ref('')
const showModal = ref(false)
const modalMessage = ref('')

// 반응형 설정을 위한 computed 속성
const { mdAndUp, smAndDown } = useDisplay()

onMounted(() => {
  // 로그인 상태 체크
  if (localStorage.getItem('isLoggedIn') === 'true') {
    router.push('/admin')
  }
})

const handleLogin = async (e) => {
  e.preventDefault()
  
  // 유효성 검사
  if (!username.value && !password.value) {
    modalMessage.value = '아이디와 비밀번호를 입력해주세요.'
    showModal.value = true
    return
  } else if (!username.value) {
    modalMessage.value = '아이디를 입력해주세요.'
    showModal.value = true
    return
  } else if (!password.value) {
    modalMessage.value = '비밀번호를 입력해주세요.'
    showModal.value = true
    return
  }

  try {
    const encryptedPassword = CryptoJS.SHA256(password.value).toString()
    
    const response = await axios.get(URL, {
      params: { 
        id: username.value, 
        pw: encryptedPassword 
      },
      withCredentials: true
    })

    if (response.status === 200) {
      const { ADMIN_ID, ADMIN_NM } = response.data.dataInfo
      localStorage.setItem('isLoggedIn', 'true')
      localStorage.setItem('adminId', ADMIN_ID)
      localStorage.setItem('adminName', ADMIN_NM)

      const redirectPath = route.query.redirect || '/admin'
      router.push(redirectPath)
    }
  } catch (err) {
    error.value = '로그인 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.'
  }
}
</script>

<template>
  <v-container class="fill-height login-container">
    <v-row justify="center" align="center">
      <v-col cols="12" md="10">
        <v-card flat class="login-card">
          <v-row class="fill-height">
            <!-- 로고 영역 -->
            <v-col cols="12" md="6" class="text-center">
              <v-img
                :src="logo"
                :max-width="$vuetify.display.mdAndUp ? '350' : $vuetify.display.smAndDown ? '200' : '250'"
                class="mx-auto topPadding"
                style="cursor: pointer"
                @click="router.push('/')"
                @load="() => console.log('로고 이미지 로드 완료')"
              />
            </v-col>

            <!-- 로그인 폼 영역 -->
            <v-col cols="12" md="6">
              <v-card-text class="topPadding">
                <v-form @submit.prevent="handleLogin" @keydown.enter="handleLogin">
                  <v-text-field
                    v-model="username"
                    label="아이디"
                    placeholder="아이디를 입력해주세요"
                    variant="outlined"
                    class="mb-2"
                    :rules="[
                      v => v.trim().length > 0 || '공백은 입력할 수 없습니다'
                    ]"
                  />
                  
                  <v-text-field
                    v-model="password"
                    label="비밀번호"
                    placeholder="비밀번호를 입력해주세요"
                    type="password"
                    variant="outlined"
                    class="mb-4"
                    :rules="[
                      v => v.trim().length > 0 || '공백은 입력할 수 없습니다'
                    ]"
                  />

                  <v-btn
                    block
                    color="black"
                    size="large"
                    class="mb-4"
                    height="56"
                    @click="handleLogin"
                  >
                    로그인
                  </v-btn>

                  <v-alert
                    v-if="error"
                    type="error"
                    class="mb-4"
                  >
                    {{ error }}
                  </v-alert>

                  <v-row justify="space-between" no-gutters>
                    <v-col cols="auto">
                      <v-btn
                        variant="text"
                        density="compact"
                        @click="router.push('/signup')"
                      >
                        회원가입
                      </v-btn>
                    </v-col>
                    <v-col cols="auto">
                      <v-btn
                        variant="text"
                        density="compact"
                        @click="router.push('/findid')"
                      >
                        ID찾기
                      </v-btn>
                    </v-col>
                    <v-col cols="auto">
                      <v-btn
                        variant="text"
                        density="compact"
                        @click="router.push('/findpw')"
                      >
                        P/W 찾기
                      </v-btn>
                    </v-col>
                  </v-row>
                </v-form>
              </v-card-text>
            </v-col>
          </v-row>
        </v-card>
      </v-col>
    </v-row>

    <!-- 모달 -->
    <v-dialog v-model="showModal" max-width="400" @keydown.enter="showModal = false">
      <v-card>
        <v-card-text class="text-center pa-4">
          {{ modalMessage }}
        </v-card-text>
        <v-card-actions class="justify-center">
          <v-btn
            color="black"
            @click="showModal = false"
          >
            확인
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<style scoped>
.v-btn {
  text-transform: none;
}

/* 컨테이너 높이 설정 */
.login-container {
  min-height: 80vh !important; /* 뷰포트 높이의 80% */
}

/* 카드 높이 설정 */
.login-card {
  min-height: 600px; 
  padding: 3rem;
}

/* 카드 영역 탑 패딩*/
.topPadding {
  padding-top: 4rem;
}
</style>
