// react-slh/src/components/HomeContact.jsx
import React, { useState, useEffect } from "react";
import { useIntersectionObserver } from "../IntersectionObserverContext";
import axios from "axios";
import { useNavigate } from "react-router-dom";

function Contact() {
    const { ref, inView } = useIntersectionObserver();
    const navigate = useNavigate();

    // 폼 데이터 저장
    const [formData, setFormData] = useState({
        orgNm: "",
        name: "",
        phone: "",
        email: "",
        service: [],
        budget: "",
        schedule: "",
        description: ""
    });

    // 오류 저장
    const [errors, setErrors] = useState({});
    // 모달 상태
    const [modalVisible, setModalVisible] = useState(false);
    const [modalMessage, setModalMessage] = useState("");
    // 서비스 목록 API
    const URL = "http://localhost:3001/apis/service/list";
    // 서비스 목록 저장
    const [services, setServices] = useState([]);

    // API 호출해서 서비스 목록 가져오기
    const fetchData = async () => {
        const response = await axios.get(URL);
        // console.log(response.data);
        setServices(response.data.dataInfo.rows);
    };

    useEffect(() => {
        fetchData();
    }, []);

    // 전화번호 하이픈 제거, 예산에서 쉼표 추가
    const handleChange = (e) => {
      const { name, value, type, checked } = e.target;
  
      if (type === "checkbox") {
          setFormData((prevData) => ({
              ...prevData,
              service: checked
                  ? [...prevData.service, value]
                  : prevData.service.filter((service) => service !== value),
          }));
      } else {
          setFormData((prevData) => ({
              ...prevData,
              [name]: type === 'text' && name === 'phone'
                  ? value.replace(/[^0-9]/g, '') // 전화번호에서 숫자만 남김
                  : (name === 'budget'
                      ? formatBudget(value) // 예산에서 쉼표 추가
                      : value)
          }));
      }
    };
  
    // 숫자를 쉼표 형식으로 변환
    const formatBudget = (value) => {
        // 숫자만 남기기
        const numericValue = value.replace(/[^0-9]/g, '');
        // 숫자에 쉼표 추가
        return numericValue === '' ? '' : Number(numericValue).toLocaleString();
    };
  

    // 전화번호 유효성 검사 함수
    const isValidPhone = (phone) => {
      // 예: 숫자만 포함하고 길이가 10자리 또는 11자리인 경우에 유효하다고 간주
      const phonePattern = /^\d{10,11}$/;
      return phonePattern.test(phone);
    };

    // 이메일 유효성 검사 함수
    const isValidEmail = (email) => {
      // 일반적인 이메일 형식에 대한 정규 표현식
      const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      return emailPattern.test(email);
    };

    // 유효성검사
    const validateForm = () => {
      const newErrors = {};
      let hasEmptyFields = false; // 모든 필드 체크를 위한 변수 초기화
  
      // 각 필드 체크
      if (!formData.orgNm.trim()) {
          newErrors.orgNm = "회사 또는 기관명을 입력해주세요.";
          hasEmptyFields = true; // 필드가 비어있으면 true
      }
      if (!formData.name.trim()) {
          newErrors.name = "담당자명을 입력해주세요.";
          hasEmptyFields = true; // 필드가 비어있으면 true
      }
      if (!formData.phone.trim()) {
          newErrors.phone = "연락처를 입력해주세요.";
          hasEmptyFields = true; // 필드가 비어있으면 true
      }
      if (!formData.email.trim()) {
          newErrors.email = "이메일을 입력해주세요.";
          hasEmptyFields = true; // 필드가 비어있으면 true
      }
      if (formData.service.length === 0) {
          newErrors.service = "최소 하나의 서비스를 선택해주세요.";
          hasEmptyFields = true; // 필드가 비어있으면 true
      }
  
      // 입력하지 않은 항목이 하나라도 있다면 모달 메시지 표시
      if (hasEmptyFields) {
          setModalMessage("입력하지 않은 항목이 있습니다. 다시 확인해주세요.");
          setModalVisible(true);
          return false; 
      }
  
      // 입력된 경우 유효성 체크
      if (!isValidPhone(formData.phone)) {
          newErrors.phone = "올바른 연락처 형식이 아닙니다."; 
      }
      if (!isValidEmail(formData.email)) {
          newErrors.email = "올바른 이메일 주소를 입력해주세요."; 
      }
  
      setErrors(newErrors);
  
      // 유효성 검사 실패 시 해당 오류 메시지 모달 표시
      if (Object.keys(newErrors).length > 0) {
        const errorMessages = Object.values(newErrors).join("<br />");
        setModalMessage("유효성 검사에 통과하지 못한 항목이 있습니다:<br />" + errorMessages);
        setModalVisible(true);
        return false; // 유효성 검사 실패
      }
  
      return true; 
      };


    // 모달 확인 버튼
    const handleModalConfirm = () => {
        setModalVisible(false);
    };

    // 폼 제출
    const handleSubmit = async (e) => {
      e.preventDefault(); // 기본제출 방지
  
      // 폼 제출 전 유효성검사
      if (!validateForm()) return;
  
      // 쉼표 제거한 budget 값을 복사
      const sanitizedFormData = {
          ...formData,
          budget: formData.budget.replace(/,/g, "") // 쉼표 제거
      };
  
      try {
          const response = await fetch("http://localhost:3001/apis/contact/postContact", {
              method: "POST",
              headers: {
                  "Content-Type": "application/json",
              },
              body: JSON.stringify(sanitizedFormData), // 쉼표 제거한 데이터 전송
          });
  
          if (response.ok) {
              setModalMessage("요청이 성공적으로 전송되었습니다.");
              setModalVisible(true);
              // 성공시 폼 데이터 초기화
              setFormData({
                  orgNm: "",
                  name: "",
                  phone: "",
                  email: "",
                  service: [],
                  budget: "",
                  schedule: "",
                  description: ""
              });
              setErrors({}); // 성공시 에러 메세지 초기화
          } else {
              setModalMessage("요청에 실패했습니다. 다시 시도해주세요.");
              setModalVisible(true);
          }
      } catch (error) {
          console.error("Error submitting form:", error);
          setModalMessage("서버 오류가 발생했습니다. 나중에 다시 시도해주세요.");
          setModalVisible(true);
      }
    };

    return (
      <section id="page04" className={`section ${inView ? 'view' : ''}`} ref={ref}>
        <div className="wrap">
          <div className="component">
            <div className="maintext">CONTACT</div>
            <span>
                아이디어만 있어도 좋아요, <br /> 소프트랩 흄과 함께 할 당신을 소개해주세요.
            </span>
          </div>
          <form className="o1000" onSubmit={handleSubmit}>
            <div className="board">
              <div className="left">
                <ul id="question">
                  <li className="number">01</li>
                  <li className="text">고객 정보</li>
                  <li className="memo">
                      * 기재하신 연락처로 담당자가 연락 또는 이메일을 드립니다.
                  </li>
                </ul>
                <ul id="answer">
                  <div className="grid">
                    <input
                        type="text"
                        name="orgNm"
                        placeholder="회사 또는 기관명"
                        value={formData.orgNm}
                        onChange={handleChange}
                    />
                    <input
                        type="text"
                        name="name"
                        placeholder="담당자명"
                        value={formData.name}
                        onChange={handleChange}
                    />
                    <input
                        type="text"
                        name="phone"
                        placeholder="연락처"
                        value={formData.phone}
                        onChange={handleChange}
                    />
                    <input
                        type="text"
                        name="email"
                        placeholder="이메일"
                        value={formData.email}
                        onChange={handleChange}
                    />
                  </div>
                </ul>
                <ul id="question">
                  <li className="number">02</li>
                  <li className="text">함께 하고 싶은 서비스는 무엇인가요?</li>
                  <li className="memo">* 중복선택가능</li>
                </ul>
                <div id="select">
                    {services.map(service => (
                      <label key={service.SERVICE_CD} className="checkbox button">
                        {service.SERVICE_NM}
                        <input
                          type="checkbox"
                          name="service"
                          value={service.SERVICE_CD}
                          onChange={handleChange}
                          hidden
                        />
                      </label>
                    ))}
                </div>
              </div>
              <div className="right">
                <ul id="question">
                  <li className="number">03</li>
                  <li className="text">프로젝트 예산 / 일정을 알려주세요.</li>
                </ul>
                <ul id="answer">
                  <div className="grid">
                    <input
                      type="text"
                      name="budget"
                      placeholder="대략적인 예산을 입력해주세요."
                      value={formData.budget}
                      onChange={handleChange}
                    />
                    <input
                      type="text"
                      name="schedule"
                      placeholder="대략적인 마감 일정을 입력해주세요. (숫자만 입력)"
                      value={formData.schedule}
                      onChange={(e) => setFormData((prevData) => ({
                        ...prevData,
                        schedule: e.target.value.replace(/[^0-9]/g, '') // 숫자만 입력 가능하게 처리
                        // todo- datepicker 사용해서 달력에서 선택하게 변경
                      }))}
                    />
                  </div>
                </ul>
                <ul id="question">
                  <li className="number">04</li>
                  <li className="text">
                      구상 중이신 프로젝트에 대해 자세히 설명해 주세요.
                  </li>
                </ul>
                <ul id="answer">
                  <textarea
                      name="description"
                      placeholder="프로젝트에 대해 설명해주세요."
                      value={formData.description}
                      onChange={handleChange}
                  />
                </ul>
              </div>
            </div>
              <div>
                  <input type="submit" value="제출" />
              </div>
          </form>
            <a 
            href="#" 
            onClick={(e) => {
              e.preventDefault(); // 새로고침 방지
              navigate('/contact');
            }} 
            className="mob_btn x1000">문의하기</a>
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>

        {/* 모달 */}
        {modalVisible && (
          <div style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 1000
          }}>
            <div style={{
              backgroundColor: 'white',
              padding: '20px',
              borderRadius: '5px',
              boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
              textAlign: 'center'
            }}>
            <p dangerouslySetInnerHTML={{ __html: modalMessage }} />
            <br />
            <input
                type="button"
                value="확인"
                onClick={handleModalConfirm}
                style={{ cursor: 'pointer' }} // 추가 스타일
            />
            </div>
          </div>
        )}
      </section>
    );
}

export default Contact;

// vue3-slh/src/components/Home/HomeContact.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import { useContactStore } from '../../stores/contact'
import { useIntersectionObserver } from '../../plugins/useIntersectionObserver'
import Modal from '../Modal.vue'

const contactStore = useContactStore()
const { isVisible, target } = useIntersectionObserver()

onMounted(() => {
  contactStore.fetchServiceData()
})

const modalShow = ref(false)
const modalType = ref('alert')
const modalTitle = ref('')
const modalMessage = ref('')

const serviceData = computed(() => contactStore.serviceData)

const submitForm = async () => {
  // 각 필수 입력 필드 검사
  if (!contactStore.orgNm || !contactStore.name || !contactStore.phone || !contactStore.email || !contactStore.selectedServices || !contactStore.budget || !contactStore.schedule || !contactStore.description) {
    showErrorModal('모든 칸을 입력해주세요.');
    return;
  }
  if (!contactStore.orgNm) {
    showErrorModal('회사 또는 기관명을 입력해주세요.');
    return;
  }
  if (!contactStore.name) {
    showErrorModal('담당자명을 입력해주세요.');
    return;
  }
  if (!contactStore.phone) {
    showErrorModal('연락처를 입력해주세요.');
    return;
  }
  if (!contactStore.email) {
    showErrorModal('이메일을 입력해주세요.');
    return;
  }
  if (contactStore.selectedServices.length === 0) {
    showErrorModal('서비스를 선택해주세요.');
    return;
  }
  if (!contactStore.budget) {
    showErrorModal('예산을 입력해주세요.');
    return;
  }
  if (!contactStore.schedule) {
    showErrorModal('일정을 입력해주세요.');
    return;
  }
  if (!contactStore.description) {
    showErrorModal('프로젝트 설명을 입력해주세요.');
    return;
  }

  const responseData = await contactStore.submitContactForm()

  modalShow.value = true
  if (responseData) {
    modalType.value = 'alert';
    modalTitle.value = '제출 완료';
    modalMessage.value = '제출이 완료되었습니다.';
  }
}

const showErrorModal = (message) => {
  modalShow.value = true;
  modalType.value = 'alert';
  modalTitle.value = '입력 확인';
  modalMessage.value = message;
}
const closeModal = () => {
  modalShow.value = false
  modalType.value = 'alert'
  modalTitle.value = ''
  modalMessage.value = ''
}

const confirmModal = () => {
  modalShow.value = false
  modalType.value = 'alert'
  modalTitle.value = ''
  modalMessage.value = ''
}

const clearServiceError = () => {
  contactStore.serviceError = null
}

contactStore.$patch({ serviceData: [] }) // 초기화
</script>

<template>
    <div ref="target">
    <section id="page04" class="section" :class="{ view: isVisible }">
      <div class="wrap">
        <div class="component">
          <div class="maintext">CONTACT</div>
          <span>아이디어만 있어도 좋아요, <br> 소프트랩 흄과 함께 할 당신을 소개해주세요.</span>
        </div>

        <div class="o1000">
          <v-form @submit.prevent="submitForm" ref="form">
            <div class="board">
              <div class="left">
                <ul id="question">
                  <li class="number">01</li>
                  <li class="text">고객 정보</li>
                  <li class="memo">* 기재하신 연락처로 담당자가 연락 또는 이메일을 드립니다.</li>
                </ul>

                <ul id="answer">
                  <div class="grid">
                    <v-text-field 
                      v-model="contactStore.orgNm"
                      label="회사 또는 기관명"
                      :rules="[v => !!v || '회사 또는 기관명을 입력해주세요', v => v.trim().length > 0 || '공백은 입력할 수 없습니다']"
                    ></v-text-field>
                    <v-text-field 
                      v-model="contactStore.name" 
                      label="담당자명" 
                      :rules="[v => !!v || '담당자명을 입력해주세요', v => v.trim().length > 0 || '공백은 입력할 수 없습니다']"
                    ></v-text-field>
                    <v-text-field 
                      v-model="contactStore.phone" 
                      label="연락처(-제외)"
                      :rules="[
                        v => !!v || '연락처를 입력해주세요',
                        v => (v.length === 10 || v.length === 11) || '연락처는 10~11자리를 입력해주세요',
                        v => v.trim().length > 0 || '공백은 입력할 수 없습니다'
                      ]"
                    ></v-text-field>
                    <v-text-field 
                      v-model="contactStore.email" 
                      type="email" 
                      label="이메일"
                      :rules="[
                        v => !!v || '이메일을 입력해주세요',
                        v => /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/.test(v) || '유효한 이메일 주소를 입력해주세요',
                        v => v.trim().length > 0 || '공백은 입력할 수 없습니다',
                        v => /^\d+$/.test(v) || '숫자만 입력해주세요'
                      ]"
                    ></v-text-field>
                  </div>
                </ul>

                <ul id="question">
                  <li class="number">02</li>
                  <li class="text">함께 하고 싶은 서비스는 무엇인가요?</li>
                  <li class="memo">* 중복선택가능</li>
                </ul>

                <div id="select">
                  <label v-for="(item, index) in serviceData" :key="index" class="checkbox button">
                    {{ item.SERVICE_NM }}
                    <input 
                      type="checkbox" 
                      name="tag" 
                      :value="item.SERVICE_CD" 
                      v-model="contactStore.selectedServices"
                      @change="clearServiceError" 
                      hidden
                    >
                  </label>
                  <div v-if="contactStore.serviceError" style="color: red;">
                    {{ contactStore.serviceError }}
                  </div>
                </div>
              </div>

              <div class="right">
                <ul id="question">
                  <li class="number">03</li>
                  <li class="text">프로젝트 예산 / 일정을 알려주세요.</li>
                </ul>

                <ul id="answer">
                  <div class="grid">
                    <div class="inlineWrapper">
                      <v-text-field
                        label="예산 입력"
                        v-model="contactStore.budget"
                        :rules="[
                          v => !!v || '예산을 입력해주세요',
                          v => v.trim().length > 0 || '공백은 입력할 수 없습니다',
                          v => /^\d+$/.test(v) || '숫자만 입력해주세요'
                        ]"
                      ></v-text-field>
                      <div class="inlineDiv"></div>
                    </div>
                    <div class="inlineWrapper">
                      <v-text-field
                        label="일정 입력"
                        v-model="contactStore.schedule"
                        :rules="[
                          v => !!v || '일정을 입력해주세요',
                          v => v.trim().length > 0 || '공백은 입력할 수 없습니다'
                        ]"
                      ></v-text-field>
                      <div class="inlineDiv"></div>
                    </div>
                  </div>
                </ul>  

                <ul id="question">
                  <li class="number">04</li>
                  <li class="text">구상 중이신 프로젝트에 대해 자세히 설명해 주세요.</li>
                </ul>

                <ul id="answer">
                  <div>
                    <span class="ex">
                      예시) <br>
                      프로젝트 제목 : 소프트랩 흄 모바일 앱 리뉴얼<br>
                      프로젝트 목적 : 기존 앱을 트렌드에 맞게 리뉴얼하고 싶습니다.<br>
                      선호하는 컨셉 : 홈페이지 주소 또는 텍스트로 입력해주세요.<br>
                      문의 내용 : 프로젝트에 대해 강조하고 싶은 내용을 입력해주세요.
                    </span>
                    <v-textarea
                      outlined
                      v-model="contactStore.description" 
                      :rules="[v => !!v || '내용을 입력해주세요', v => v.trim().length > 0 || '공백은 입력할 수 없습니다']"
                    ></v-textarea>
                  </div>
                </ul>
              </div>
            </div>
            <input type="submit" name="제출">
          </v-form>
        </div>

        <router-link to="/contactDetail" class="mob_btn x1000">문의하기</router-link>
        <br>
        <br>
        <br>
        <br>
        <br>
      </div>
    </section>
    <Modal
      :title="modalTitle"
      :message="modalMessage"
      v-model:show="modalShow"
      :mode="modalType"
      @confirm="confirmModal"
      @closeDialog="closeModal"
    />
  </div>
</template>

<style scoped>
.inlineWrapper {
  display: flex;
  align-items: center;
  margin-bottom: 16px;
}

:deep(.v-text-field__details) {
  overflow: visible !important;
}

:deep(.v-messages__wrapper) {
  white-space: normal !important;
}

:deep(.v-messages__message) {
  word-wrap: break-word !important;
  color: red !important;
}
</style>
