// vue3-slh/src/components/Admin/AdminAbout.vue
<script setup>
import { ref, onMounted, reactive } from 'vue'
import axios from 'axios'
import Modal from '../Modal.vue'
import { useSelectedAboutId } from '../../stores/about'

const selectedAboutId = useSelectedAboutId()

const props = defineProps({
  onSelect: {
    type: Function,
    required: true
  }
})

const URL = "http://localhost:3001/apis/about"
const URL2 = "http://localhost:3001/apis/about/deleteAbout"

const data = ref([])
const loading = ref(false)
const error = ref(null)
const dialog = ref(false)  
const dialogProps = reactive({  
  title: '',
  message: '',
  mode: 'alert',
  action: null  
})

const fetchData = async () => {
  try {
    error.value = null
    loading.value = true
    const response = await axios.get(URL)
    data.value = response.data.dataInfo.rows
  } catch (e) {
    error.value = e
  }
  loading.value = false
}

onMounted(() => {
  fetchData()
})

const showConfirmDialog = (title, message, confirmAction) => {
  dialogProps.title = title
  dialogProps.message = message
  dialogProps.mode = 'confirm'
  dialogProps.action = confirmAction
  dialog.value = true
}

const showAlertDialog = (title, message) => {
  dialogProps.title = title
  dialogProps.message = message
  dialogProps.mode = 'alert'
  dialogProps.action = null
  dialog.value = true
}

const handleDelete = async (id) => {
  showConfirmDialog(
    "소개글 삭제",
    "정말로 이 소개글을 삭제하시겠습니까?",
    async () => {
      try {
        dialog.value = false  // 모달 닫기
        const response = await axios.delete(`${URL2}?id=${id}`, {
          headers: {
            'accept': 'application/json'
          }
        })
        
        if (!response.data.error) {
          await fetchData()
          showAlertDialog("성공", "소개글이 성공적으로 삭제되었습니다.")
        } else {
          showAlertDialog("오류", `소개글 삭제에 실패했습니다: ${response.data.error}`)
        }
      } catch (error) {
        console.error("Error deleting about:", error)
        showAlertDialog("오류", "소개글 삭제 중 오류가 발생했습니다.")
      }
    }
  )
}

const handleUpdate = (id) => {
  selectedAboutId.selectedAboutId = id
  props.onSelect('updateabout')
}

</script>

<template>
  <v-container fluid class="pa-4">
    <v-row>
      <v-col cols="12">
        <h2 class="text-h5 font-weight-bold mb-4">소개글 조회</h2>
        
        <div class="d-flex justify-end mb-4">
          <v-btn
            color="black"
            @click="props.onSelect('addabout')"
            class="white--text"
          >
            추가
          </v-btn>
        </div>

        <v-table>
          <thead>
            <tr>
              <th class="text-center black white--text">제목</th>
              <th class="text-center black white--text">내용</th>
              <th class="text-center black white--text"></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in data" :key="row.ID">
              <td>{{ row.TITLE }}</td>
              <td>{{ row.SUB_TITLE }}</td>
              <td>
                <div class="d-flex justify-center gap-2">
                  <v-btn
                    color="grey-darken-3"
                    class="white--text mr-2"
                    @click="handleUpdate(row.ID)"
                  >
                    수정
                  </v-btn>
                  <v-btn
                    color="grey-darken-3"
                    class="white--text"
                    @click="handleDelete(row.ID)"
                  >
                    삭제
                  </v-btn>
                </div>
              </td>
            </tr>
          </tbody>
        </v-table>
      </v-col>
    </v-row>

    <v-dialog v-model="dialog" max-width="500px">
      <v-card>
        <v-card-title>{{ dialogProps.title }}</v-card-title>
        <v-card-text>{{ dialogProps.message }}</v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn 
            v-if="dialogProps.mode === 'alert'" 
            color="primary" 
            @click="dialog = false"
          >
            확인
          </v-btn>
          <template v-else>
            <v-btn 
              color="primary" 
              @click="dialogProps.action"
            >
              확인
            </v-btn>
            <v-btn 
              color="error" 
              @click="dialog = false"
            >
              취소
            </v-btn>
          </template>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<style scoped>
.v-table {
  border: 1px solid rgba(0, 0, 0, 0.12);
}

.gap-2 {
  gap: 8px;
}

@media (max-width: 600px) {
  .d-flex {
    flex-direction: column;
  }
  
  .gap-2 {
    gap: 4px;
  }
  
  .v-btn {
    width: 100%;
    margin-right: 0 !important;
    margin-bottom: 4px;
  }
}
</style>

// react-slh/src/components/AdminAbout.jsx
import React, { useState, useEffect } from "react";
import { Box, Button, Typography, Paper, Table, TableCell, TableContainer, TableHead, TableRow, TableBody } from "@mui/material"; 
import axios from "axios";
import { useSetRecoilState } from 'recoil';
import { selectedAboutIdState } from '../atoms';
import Modal from "./Modal";

function AdAbout({ setSelectedNav }) {
  const setSelectedAboutId = useSetRecoilState(selectedAboutIdState);
  const URL = "http://localhost:3001/apis/about";
  const URL2 = "http://localhost:3001/apis/about/deleteAbout";
  
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [showModal, setShowModal] = useState(false);
  const [modalProps, setModalProps] = useState({});

  const fetchData = async () => {
    try {
      setError(null);
      setLoading(true);

      const response = await axios.get(URL);
      setData(response.data.dataInfo.rows);
    } catch (e) {
      setError(e);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchData();
  }, []);

  const showConfirmModal = (title, message, confirmAction) => {
    setModalProps({ 
      title, 
      message, 
      mode: "confirm", 
      onConfirm: () => {
        confirmAction();
        setShowModal(false);
      },
      onCancel: () => setShowModal(false)
    });
    setShowModal(true);
  };

  const showAlertModal = (title, message) => {
    setModalProps({ 
      title, 
      message, 
      mode: "alert",
      onConfirm: () => setShowModal(false)
    });
    setShowModal(true);
  };

  const handleDelete = async (id) => {
    // 소개글 삭제시 에러를 반환하지 않을 경우 성공처리로 변경
    showConfirmModal(
      "소개글 삭제",
      "정말로 이 소개글을 삭제하시겠습니까?",
      async () => {
        try {
          const response = await axios.delete(`${URL2}?id=${id}`, {
            headers: {
              'accept': 'application/json'
            }
          });
          
          if (!response.data.error) {
            showAlertModal("성공", "소개글이 성공적으로 삭제되었습니다.");
            fetchData(); // 데이터 다시 불러오기
          } else {
            showAlertModal("오류", `소개글 삭제에 실패했습니다: ${response.data.error}`);
          }
        } catch (error) {
          console.error("Error deleting about:", error);
          showAlertModal("오류", "소개글 삭제 중 오류가 발생했습니다.");
        }
      }
    );
  };

  const tableStyle = {
    overflow: 'hidden',
    '& .MuiTable-root': {
      width: '100%',
    },
    '& .MuiTableCell-root': {
      color: 'black',
      borderBottom: '1px solid rgba(224, 224, 224, 1)',
      padding: { xs: '8px', sm: '16px' }, // 반응형 패딩
    },
    '& .MuiTableRow-root': {
      opacity: 1,
      '&:hover': {
        opacity: 1,
      },
    },
    '& .MuiTableHead-root .MuiTableCell-root': {
      color: 'white',
      backgroundColor: 'black',
      borderBottom: '1px solid white',
      '&:first-of-type': {
        borderRight: '1px solid white',
      },
    },
    '& .always-visible': {
      opacity: 1,
      '&:hover': {
        opacity: 1,
      },
    },
  };
  
  return(
    <Box sx={{ 
      mt: 2, 
      px: { xs: 1, sm: 2 }, // 반응형 패딩
      width: '100%', 
      maxWidth: '1200px', 
      margin: '0 auto',
      overflowX: 'auto' // 작은 화면에서 가로 스크롤 허용
    }}>
      <Typography variant="h5" sx={{ mb: 2, fontWeight: "bold" }}>
        소개글 조회
      </Typography>
      <Box sx={{ 
        display: "flex", 
        mb: 2, 
        alignItems: "center", 
        justifyContent: "flex-end",
        flexWrap: 'wrap' // 작은 화면에서 버튼 줄바꿈
      }}>
        <Box>
          <Button 
            variant="contained" 
            onClick={() => setSelectedNav('addabout')}
            sx={{ 
              mr: { xs: 1, sm: 2 }, // 반응형 마진
              mb: { xs: 1, sm: 0 }, // 작은 화면에서 아래 마진 추가
              bgcolor: 'black', 
              color: 'white',
              '&:hover': {
                bgcolor: 'rgba(0, 0, 0, 0.8)',
              }
            }}
          >추가
          </Button>
        </Box>
      </Box>
      <TableContainer component={Paper}>
        <Table sx={tableStyle}>
          <TableHead>
            <TableRow>
              <TableCell align="center" sx={{ width: { xs: "30%", sm: "20%" }, fontWeight: 'bold' }}>제목</TableCell>
              <TableCell align="center" sx={{ width: { xs: "40%", sm: "60%" }, fontWeight: 'bold' }}>내용</TableCell>
              <TableCell align="center" sx={{ width: { xs: "30%", sm: "20%" }, fontWeight: 'bold' }}></TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {data.map((row) => (
              <TableRow key={row.ID} className="always-visible">
                <TableCell align="left" sx={{ cursor: 'default !important' }}>{row.TITLE}</TableCell>
                <TableCell align="left" sx={{ cursor: 'default !important' }}>{row.SUB_TITLE}</TableCell>
                <TableCell align="center">
                  <Box sx={{ 
                    display: "flex", 
                    justifyContent: "center",
                    flexDirection: { xs: 'column', sm: 'row' }, // 작은 화면에서 버튼 세로 배치
                    gap: { xs: 1, sm: 0 } // 작은 화면에서 버튼 사이 간격
                  }}>
                    <Button 
                      variant="contained" 
                      onClick={() => {
                        setSelectedAboutId(row.ID);
                        setSelectedNav('updateabout');
                      }}
                      sx={{ 
                        bgcolor: 'rgba(0, 0, 0, 0.5)', 
                        color: 'white',
                        '&:hover': {
                          bgcolor: 'rgba(0, 0, 0, 1)',
                        },
                        mr: { xs: 0, sm: 1 },  // 반응형 마진
                        mb: { xs: 1, sm: 0 },  // 작은 화면에서 아래 마진 추가
                        width: { xs: '100%', sm: 'auto' } // 작은 화면에서 전체 너비
                      }}
                    >
                      수정
                    </Button>
                    <Button 
                      variant="contained"
                      onClick={() => handleDelete(row.ID)}
                      sx={{ 
                        bgcolor: 'rgba(0, 0, 0, 0.5)', 
                        color: 'white',
                        '&:hover': {
                          bgcolor: 'rgba(0, 0, 0, 1)',
                        },
                        width: { xs: '100%', sm: 'auto' } // 작은 화면에서 전체 너비
                      }}
                    >
                      삭제
                    </Button>
                  </Box>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
      <Modal
        open={showModal}
        onClose={() => setShowModal(false)}
        {...modalProps}
      />
    </Box>
  );
}

export default AdAbout;
