// nuxt3-slh-ver2/components/Admin/AdminAddProject.vue
<script setup>
import { ref, onMounted, reactive } from 'vue'
import axios from 'axios'
import { useRouter } from 'vue-router'

const router = useRouter()


const addProjectApi = "/api/project/add"
const fileUploadApi = "/api/upload/single"
const multiFileUploadApi = "/api/upload/multi"

// 상태 관리
const title = ref("")
const subTitle = ref("")
const stack = ref([])
const content = ref("")
const mainImage = ref(null)
const mainImagePreviewUrl = ref("")
const exampleImages = ref([])
const dialog = ref(false)
const dialogProps = reactive({
  title: '',
  message: '',
  mode: 'alert',
  action: null
})
const fileInputRef = ref(null)
const exampleImagesInputRef = ref(null)
const stackData = ref([])
const exampleImageFiles = ref([])
const exampleImageNames = ref([])

// 메인 이미지 업로드 처리
const handleMainImageUpload = (event) => {
  const file = event.target.files[0]
  if (file && !file.type.startsWith("image/")) {
    showErrorDialog("오류", "이미지 파일만 선택할 수 있습니다.")
    event.target.value = ""
    return
  }
  mainImage.value = file
  const reader = new FileReader()
  reader.onloadend = () => {
    mainImagePreviewUrl.value = reader.result
  }
  reader.readAsDataURL(file)
}

// 메인 이미지 초기화
const clearMainImage = () => {
  mainImage.value = null
  mainImagePreviewUrl.value = ""
  if (fileInputRef.value) fileInputRef.value.value = ""
}

// 예시 이미지 업로드 처리
const handleExampleImagesUpload = (event) => {
  const files = Array.from(event.target.files)
  const newImageFiles = []
  const newImageNames = []

  files.forEach(file => {
    if (file && file.type.startsWith('image/')) {
      newImageFiles.push(file)
      newImageNames.push(file.name)
      
      const reader = new FileReader()
      reader.onload = (e) => {
        exampleImages.value = [
          ...exampleImages.value,
          { file, preview: e.target.result }
        ]
      }
      reader.readAsDataURL(file)
    } else {
      showErrorDialog("오류", "이미지 파일만 선택할 수 있습니다.")
    }
  })

  exampleImageFiles.value = [...exampleImageFiles.value, ...newImageFiles]
  exampleImageNames.value = [...exampleImageNames.value, ...newImageNames]
}

// 예시 이미지 제거
const handleRemoveExampleImage = (index) => {
  exampleImageFiles.value = exampleImageFiles.value.filter((_, i) => i !== index)
  exampleImageNames.value = exampleImageNames.value.filter((_, i) => i !== index)
  exampleImages.value = exampleImages.value.filter((_, i) => i !== index)
}

// 다이얼로그 표시 함수들
const showErrorDialog = (title, message) => {
  dialogProps.title = title
  dialogProps.message = message
  dialogProps.mode = 'alert'
  dialog.value = true
}

const showConfirmDialog = (title, message, confirmAction) => {
  dialogProps.title = title
  dialogProps.message = message
  dialogProps.mode = 'confirm'
  dialogProps.action = confirmAction
  dialog.value = true
}

// 폼 제출 처리
const handleSubmit = (event) => {
  event.preventDefault()
  if (!title.value || !stack.value.length || !content.value || !mainImage.value || !exampleImages.value.length) {
    showErrorDialog("오류", "모든 필드를 입력해주세요.")
    return
  }

  showConfirmDialog("프로젝트 추가", "프로젝트를 추가하시겠습니까?", submitProject)
}

// 프로젝트 데이터 제출
const submitProject = async () => {
  try {
    // 대표 이미지 업로드
    const mainImageFormData = new FormData()
    mainImageFormData.append("file", mainImage.value)
    const mainImageResponse = await axios.post(fileUploadApi, mainImageFormData, {
      headers: { "Content-Type": "multipart/form-data" }
    })
    const mainImageUrl = mainImageResponse.data.url

    // 예시 이미지 업로드
    const exampleImagesFormData = new FormData()
    exampleImageFiles.value.forEach((file) => {
      exampleImagesFormData.append('files', file)
    })
    const exampleImagesResponse = await axios.post(multiFileUploadApi, exampleImagesFormData, {
      headers: { 
        'accept': 'application/json',
        "Content-Type": "multipart/form-data"
      }
    })

    let fileUrls = []
    if (exampleImagesResponse.data?.files) {
      fileUrls = exampleImagesResponse.data.files.map(file => file.url)
    }

    const projectData = {
      title: title.value,
      subTitle: subTitle.value,
      projectImg: mainImageUrl,
      stack: stack.value,
      projectInfo: content.value,
      files: fileUrls.map((url, index) => ({
        url: url,
        sort: index
      }))
    }

    await axios.post(addProjectApi, projectData, {
      headers: {
        'Content-Type': 'application/json'
      }
    })

    showErrorDialog("성공", "프로젝트가 추가되었습니다.")
    resetForm()
    router.push("/admin/project")
  } catch (error) {
    console.error("Error adding project:", error)
    showErrorDialog("오류", "프로젝트 추가 실패")
  }
}

// 폼 초기화
const resetForm = () => {
  title.value = ""
  subTitle.value = ""
  stack.value = []
  content.value = ""
  clearMainImage()
  exampleImages.value = []
}

// 스택 데이터 로드
onMounted(async () => {
  try {
    const response = await axios.get('/api/stack')
    stackData.value = response.data
  } catch (error) {
    console.error('스택 데이터 로드 오류:', error)
  }
})
</script>

<template>
  <v-container fluid class="pa-4">
    <h2 class="text-h5 font-weight-bold mb-4">프로젝트 추가</h2>
    
    <v-card class="pa-4">
      <form @submit.prevent="handleSubmit">
        <v-row>
          <v-col cols="12" sm="2">
            <div class="text-subtitle-1">제목<span class="required">*</span></div>
          </v-col>
          <v-col cols="12" sm="10">
            <v-text-field
              v-model="title"
              variant="outlined"
              density="comfortable"
            />
          </v-col>
          
          <v-col cols="12" sm="2">
            <div class="text-subtitle-1">부제목</div>
          </v-col>
          <v-col cols="12" sm="10">
            <v-text-field
              v-model="subTitle"
              variant="outlined"
              density="comfortable"
            />
          </v-col>
          
          <v-col cols="12" sm="2">
            <div class="text-subtitle-1">내용<span class="required">*</span></div>
          </v-col>
          <v-col cols="12" sm="10">
            <v-textarea
              v-model="content"
              variant="outlined"
              rows="4"
              no-resize
            />
          </v-col>
          
          <v-col cols="12" sm="2">
            <div class="text-subtitle-1">기술 스택 <span class="required">*</span></div>
          </v-col>
          <v-col cols="12" sm="10" class="stack-container">
            <v-row dense>
              <v-col 
                v-for="item in stackData" 
                :key="item.ID"
                cols="auto"
              >
                <v-checkbox
                  v-model="stack"
                  :label="item.STACK_NM"
                  :value="item.STACK_NM"
                />
              </v-col>
            </v-row>
          </v-col>
          
          <v-col cols="12">
            <p class="text-subtitle-1 mb-2">메인 이미지 <span class='required'>*</span></p>
            <v-file-input
              ref="fileInputRef"
              accept="image/*"
              @change="handleMainImageUpload"
              variant="outlined"
              density="comfortable"
            />
            <v-img
              v-if="mainImagePreviewUrl"
              :src="mainImagePreviewUrl"
              max-height="200"
              contain
              class="mt-2"
            >
              <template v-slot:placeholder>
                <v-row align="center" justify="center">
                  <v-progress-circular indeterminate />
                </v-row>
              </template>
            </v-img>
          </v-col>
          
          <v-col cols="12">
            <p class="text-subtitle-1 mb-2">예시 이미지 <span class='required'>*</span></p>
            <v-file-input
              ref="exampleImagesInputRef"
              accept="image/*"
              multiple
              @change="handleExampleImagesUpload"
              variant="outlined"
              density="comfortable"
            />
            <v-row v-if="exampleImages.length > 0" class="mt-2">
              <v-col 
                v-for="(image, index) in exampleImages"
                :key="index"
                cols="12"
                sm="4"
              >
                <v-card>
                  <v-img
                    :src="image.preview"
                    height="300"
                    contain
                  >
                    <template v-slot:placeholder>
                      <v-row align="center" justify="center">
                        <v-progress-circular indeterminate />
                      </v-row>
                    </template>
                  </v-img>
                  <v-btn
                    icon
                    color="black"
                    class="position-absolute close-btn"
                    @click="handleRemoveExampleImage(index)"
                  >
                    <v-icon color="black">mdi-close</v-icon>
                  </v-btn>
                </v-card>
              </v-col>
            </v-row>
          </v-col>
          
          <v-col cols="12">
            <v-btn
              type="submit"
              color="black"
              block
            >
              추가
            </v-btn>
          </v-col>
        </v-row>
      </form>
    </v-card>

    <v-dialog
      v-model="dialog"
      max-width="500px"
    >
      <v-card>
        <v-card-title>{{ dialogProps.title }}</v-card-title>
        <v-card-text>{{ dialogProps.message }}</v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn
            v-if="dialogProps.mode === 'alert'"
            color="primary"
            @click="dialog = false"
          >
            확인
          </v-btn>
          <template v-else>
            <v-btn
              color="primary"
              @click="dialogProps.action"
            >
              확인
            </v-btn>
            <v-btn
              color="error"
              @click="dialog = false"
            >
              취소
            </v-btn>
          </template>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-container>
</template>

<style scoped>
.v-card {
  border-radius: 8px;
}

.v-btn {
  text-transform: none;
}

.required {
  color: red;
  margin-left: 2px;
}

.stack-container {
  border: 1px solid #ccc;
}

.position-relative {
  position: relative;
}

.position-absolute {
  position: absolute;
}
.preview-container {
  position: relative;
  overflow: hidden;
}

.close-btn {
  position: absolute !important;
  top: 8px;
  right: 8px;
  background-color: rgba(255, 255, 255, 0.8) !important;
  min-width: auto !important;  
  width: 36px !important;      
  height: 36px !important;     
  padding: 0 !important;   
}

.file-input {
  padding: 8px 0;
}

.stack-container :deep(.v-row) {
  margin: 0; /* v-row의 기본 마진 제거 */
  gap: 0;
}

.stack-container :deep(.v-col) {
  padding-top: 0px;    /* v-col의 패딩 조정 */
  padding-bottom: 0px;
}

/* checkbox 자체의 마진도 조정 */
.stack-container :deep(.v-checkbox) {
  margin: 0;
  padding: 0;
}
@media (max-width: 600px) {
  .v-btn:not(.close-btn) {
    width: 100%;
  }
  
  .preview-container {
    width: 100%;
  }
  
  /* 다이얼로그 버튼 스타일 */
  :deep(.v-card-actions) {
    flex-direction: column;
    gap: 8px;
    padding: 16px;
  }

  :deep(.v-card-actions .v-btn) {
    width: 100%;
    margin: 0 !important;
  }
}
</style>

// react-slh/src/components/AdminAddProject.jsx
import React, { useState, useRef, useEffect, useCallback } from "react";
import { Box, TextField, Button, Typography, Paper, Grid, IconButton, Checkbox, FormControlLabel, useTheme, useMediaQuery } from "@mui/material";
import CloseIcon from '@mui/icons-material/Close';
import axios from "axios";
import Modal from "./Modal";
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Pagination } from 'swiper/modules';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

function AddProject({ setSelectedNav }) {
  const URL = "http://localhost:3001/apis/project/addProject";
  const MULTI_UPLOAD_URL = "http://localhost:3001/apis/multiFileUpload";
  
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  const [title, setTitle] = useState("");
  const [subTitle, setSubTitle] = useState(""); 
  const [stack, setStack] = useState([]);
  const [content, setContent] = useState("");
  const [mainImage, setMainImage] = useState(null);
  const [mainImagePreviewUrl, setMainImagePreviewUrl] = useState("");
  const [exampleImages, setExampleImages] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [modalProps, setModalProps] = useState({});
  const fileInputRef = useRef(null);
  const exampleImagesInputRef = useRef(null);
  const [stackData, setStackData] = useState([]);
  const [exampleImageFiles, setExampleImageFiles] = useState([]);
  const [exampleImageNames, setExampleImageNames] = useState([]);

  const handleMainImageUpload = (event) => {
    const file = event.target.files[0];
    if (file && !file.type.startsWith("image/")) {
      showErrorModal("오류", "이미지 파일만 선택할 수 있습니다.");
      event.target.value = "";
      return;
    }
    setMainImage(file);
    const reader = new FileReader();
    reader.onloadend = () => {
      setMainImagePreviewUrl(reader.result);
    };
    reader.readAsDataURL(file);
  };

  const clearMainImage = () => {
    setMainImage(null);
    setMainImagePreviewUrl("");
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleExampleImagesUpload = useCallback((event) => {
    const files = Array.from(event.target.files);
    const newImageFiles = [];
    const newImageNames = [];

    files.forEach(file => {
      if (file && file.type.startsWith('image/')) {
        newImageFiles.push(file);
        newImageNames.push(file.name);
        
        const reader = new FileReader();
        reader.onload = (e) => {
          setExampleImages(prevImages => [
            ...prevImages,
            { file, preview: e.target.result }
          ]);
        };
        reader.readAsDataURL(file);
      } else {
        showErrorModal("오류", "이미지 파일만 선택할 수 있습니다.");
      }
    });

    setExampleImageFiles(prevFiles => [...prevFiles, ...newImageFiles]);
    setExampleImageNames(prevNames => [...prevNames, ...newImageNames]);
  }, []);

  const handleRemoveExampleImage = useCallback((index) => {
    setExampleImageFiles(prevFiles => prevFiles.filter((_, i) => i !== index));
    setExampleImageNames(prevNames => prevNames.filter((_, i) => i !== index));
    setExampleImages(prevImages => prevImages.filter((_, i) => i !== index));
  }, []);

  const showErrorModal = (title, message) => {
    setModalProps({ title, message, mode: "alert" });
    setShowModal(true);
  };

  const showConfirmModal = (title, message, confirmAction) => {
    setModalProps({ title, message, mode: "confirm", onConfirm: confirmAction });
    setShowModal(true);
  };

  const handleSubmit = (event) => {
    event.preventDefault();
    if (!title || !stack || !content || !mainImage || exampleImages.length === 0) {
      showErrorModal("오류", "모든 필드를 입력해주세요.");
      return;
    }

    showConfirmModal("프로젝트 추가", "프로젝트를 추가하시겠습니까?", submitProject);
  };

  const submitProject = async () => {
    try {
      // 대표 이미지 업로드
      const mainImageFormData = new FormData();
      mainImageFormData.append("file", mainImage);
      const mainImageResponse = await axios.post("http://localhost:3001/apis/fileUpload", mainImageFormData, {
        headers: { "Content-Type": "multipart/form-data" }
      });
      console.log(mainImageResponse);
      // 대표 이미지 URL을 문자열로 저장
      const mainImageUrl = mainImageResponse.data.url;
      
      // 적용 예시 이미지 업로드
      const exampleImagesFormData = new FormData();
      console.log("exampleImagesFormData1", exampleImagesFormData);
      exampleImageFiles.forEach((file) => {
        exampleImagesFormData.append('files', file);
      });
      const exampleImagesResponse = await axios.post(MULTI_UPLOAD_URL, exampleImagesFormData, {
        headers: { 
          'accept': 'application/json',
          "Content-Type": "multipart/form-data"
         }
      });

      // 응답에서 파일 URL 추출
      let fileUrls = [];
      if (exampleImagesResponse.data && exampleImagesResponse.data.files) {
        fileUrls = exampleImagesResponse.data.files.map(file => file.url);
      } else {
        console.error("Unexpected response format for example images:", exampleImagesResponse.data);
      }
      
      console.log(mainImageResponse.data.url);
      const projectData = {
        title: title,
        subTitle: subTitle,
        projectImg: mainImageUrl,
        stack: stack,
        projectInfo: content,
        files: fileUrls.map((url, index) => ({
          url: url,
          sort: index
        }))
      };

      const response = await axios.post(URL, projectData, {
        headers: {
          'Content-Type': 'application/json'
        }
      });
      console.log(response.data);

      showErrorModal("성공", "프로젝트가 추가되었습니다.");
      setTitle("");
      setSubTitle("");
      setStack("");
      setContent("");
      clearMainImage();
      setExampleImages([]);
      setSelectedNav("project");
    } catch (error) {
      console.error("Error adding project:", error);
      showErrorModal("오류", "프로젝트 추가 실패");
    }
  };

  useEffect(() => {
    const fetchStackData = async () => {
      try {
        const response = await axios.get('http://localhost:3001/apis/stack');
        setStackData(response.data);
      } catch (error) {
        console.error('스택 데이터 로드 오류:', error);
      }
    };
    fetchStackData();
  }, []);

  return (
    <Box sx={{ width: '100%' }}>
      <Typography variant="h5" sx={{ mb: 2, fontWeight: "bold" }}>
        프로젝트 추가
      </Typography>
      <Paper elevation={3} sx={{ p: 3 }}>
        <form onSubmit={handleSubmit}>
          <Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, alignItems: { xs: 'flex-start', sm: 'center' }, mb: 2 }}>
            <Typography variant="subtitle1" sx={{ width: { xs: '100%', sm: '120px' }, mr: { xs: 0, sm: 2 }, mb: { xs: 1, sm: 0 } }}>제목</Typography>
            <TextField
              fullWidth
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              variant="outlined"
            />
          </Box>
          <Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, alignItems: { xs: 'flex-start', sm: 'center' }, mb: 2 }}>
            <Typography variant="subtitle1" sx={{ width: { xs: '100%', sm: '120px' }, mr: { xs: 0, sm: 2 }, mb: { xs: 1, sm: 0 } }}>부제목</Typography>
            <TextField
              fullWidth
              value={subTitle}
              onChange={(e) => setSubTitle(e.target.value)}
              variant="outlined"
            />
          </Box>
          <Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, mb: 2 }}>
            <Typography variant="subtitle1" sx={{ width: { xs: '100%', sm: '120px' }, mr: { xs: 0, sm: 2 }, mb: { xs: 1, sm: 0 } }}>내용</Typography>
            <TextField
              fullWidth
              multiline
              rows={4}
              value={content}
              onChange={(e) => setContent(e.target.value)}
              variant="outlined"
            />
          </Box>
          <Box sx={{ mb: 2 }}>
            <Typography variant="subtitle1" sx={{ mb: 1 }}>사용 기술</Typography>
            <Grid container spacing={2}>
              {stackData.map((item) => (
                <Grid item key={item.ID}>
                  <FormControlLabel
                    control={
                      <Checkbox
                        checked={stack.includes(item.STACK_NM)}
                        onChange={() => {
                          if (stack.includes(item.STACK_NM)) {
                            setStack(stack.filter(s => s !== item.STACK_NM));
                          } else {
                            setStack([...stack, item.STACK_NM]);
                          }
                        }}
                      />
                    }
                    label={item.STACK_NM}
                  />
                </Grid>
              ))}
            </Grid>
          </Box>
          <Box sx={{ mb: 2 }}>
            <Typography variant="subtitle1" sx={{ mb: 1 }}>메인 이미지</Typography>
            <input
              accept="image/*"
              type="file"
              onChange={handleMainImageUpload}
              ref={fileInputRef}
            />
            {mainImagePreviewUrl && (
              <Box sx={{ mt: 2, display: 'flex', justifyContent: 'center', width: '100%' }}>
                <Box sx={{ position: 'relative', width: 'fit-content' }}>
                  <img src={mainImagePreviewUrl} alt="Main Preview" style={{ maxWidth: '100%', maxHeight: '200px' }} />
                  <IconButton
                    onClick={clearMainImage}
                    sx={{
                      position: 'absolute',
                      top: 5,
                      right: 5,
                      bgcolor: 'rgba(0, 0, 0, 0.5)',
                      color: 'white',
                      '&:hover': { bgcolor: 'rgba(0, 0, 0, 0.7)' },
                    }}
                  >
                    <CloseIcon />
                  </IconButton>
                </Box>
              </Box>
            )}
          </Box>
          <Box sx={{ mb: 2 }}>
            <Typography variant="subtitle1" sx={{ mb: 1 }}>예시 이미지</Typography>
            <input
              accept="image/*"
              type="file"
              multiple
              onChange={handleExampleImagesUpload}
              ref={exampleImagesInputRef}
            />
            {exampleImages.length > 0 && (
              <Box sx={{ mt: 2, position: 'relative', '& .swiper-button-next, & .swiper-button-prev': { color: '#000' } }}>
                <Swiper
                  modules={[Navigation, Pagination]}
                  spaceBetween={10}
                  slidesPerView={isMobile ? 1 : 3}
                  navigation
                  pagination={{ clickable: true }}
                >
                  {exampleImages.map((image, index) => (
                    <SwiperSlide key={index}>
                      <Box sx={{ position: 'relative', width: '100%', paddingTop: '75%' }}>
                        <img 
                          src={image.preview} 
                          alt={`Example ${index + 1}`} 
                          style={{ 
                            position: 'absolute', 
                            top: 0, 
                            left: 0, 
                            width: '100%', 
                            height: '100%', 
                            objectFit: 'contain' 
                          }} 
                        />
                        <IconButton
                          onClick={() => handleRemoveExampleImage(index)}
                          sx={{
                            position: 'absolute',
                            top: 5,
                            right: 5,
                            bgcolor: 'rgba(0, 0, 0, 0.5)',
                            color: 'white',
                            '&:hover': { bgcolor: 'rgba(0, 0, 0, 0.7)' },
                          }}
                        >
                          <CloseIcon />
                        </IconButton>
                      </Box>
                    </SwiperSlide>
                  ))}
                </Swiper>
              </Box>
            )}
          </Box>
          <Button
            type="submit"
            variant="contained"
            sx={{ mt: 2, bgcolor: 'black', color: 'white', '&:hover': { bgcolor: 'rgba(0, 0, 0, 0.8)' } }}
          >
            추가
          </Button>
        </form>
      </Paper>
      <Modal
        open={showModal}
        onClose={() => setShowModal(false)}
        {...modalProps}
      />
    </Box>
  );
}

export default AddProject;
