// nuxt3-slh-ver2/components/Home/HomeAbout.vue
<script setup>
import { ref, onMounted } from 'vue'
import axios from 'axios'
import { useIntersectionObserver } from '@vueuse/core'

const isVisible = ref(false)
const target = ref(null)

// vue3와 다르게 옵저버 사용, isVisible 상태 변경 시 콜백 함수 실행
useIntersectionObserver(target, ([{ isIntersecting }]) => {
  isVisible.value = isIntersecting
})

const data = ref([])
const error = ref(null)
const loading = ref(false)

const { data: aboutData } = await useFetch('/api/about')

// aboutData가 변경될 때마다 data ref 업데이트
watchEffect(() => {
  if (aboutData.value?.dataInfo) {
    data.value = aboutData.value.dataInfo
  }
})
</script>

<template>
  <div ref="target">
    <section id="page02" class="section" :class="{ view: isVisible }">
        <div class="wrap">
            <div class="component">
                <div class="maintext">About</div>
                <span>" 사람을 위한 실용적인 기술을 만드는 소프트랩 흄 입니다. "</span>
            </div>

            <ul class="grid">
                <li v-for="(item, index) in data" :key="index">
                    <img :src="item.ICON" alt="" />
                    <div class="name">{{ item.TITLE }}</div>
                    <div class="subname">{{ item.SUB_TITLE }}</div>
                </li>
            </ul>
        </div>
    </section>
  </div>
</template>

<style scoped>

</style>

// react-slh/src/components/HomeAbout.jsx
import React, {useState, useEffect} from "react";
import { useIntersectionObserver } from "../IntersectionObserverContext";
import axios from 'axios';

function About() {
    const {ref, inView } = useIntersectionObserver();
    const URL =
    "http://localhost:3001/apis/about";
    // About 소개글 조회

    const [data, setData] = useState([]);
    const [loding, setLoding] = useState([]);
    const [error, setError] = useState([]);

    const fetchData = async () => {
        try {
            setError(null);
            setLoding(true);

            const response = await axios.get(URL);
            // console.log(response.data);
            // 응답 데이터 확인, 전체 출력
            // 확인완료 주석처리 2024-10-08, 10:26
            setData(response.data.dataInfo.rows);

        } catch(e) {
            setError(e);
        }
        setLoding(false);
    };
    useEffect(() => {
        fetchData();
    }, []);



    return(
        <section id="page02" className={`section ${inView ? 'view' : ''}`} ref={ref}>
            <div className="wrap">
                <div className="component">
                    <div className="maintext">About</div>
                    <span>" 사람을 위한 실용적인 기술을 만드는 소프트랩 흄 입니다. "</span>
                </div>

                <ul className="grid">
                    {data && data.map((item, index) => (
                        <li key={index}>
                            <img src={item.ICON} alt="" />
                            <div className="name">{item.TITLE}</div>
                            <div className="subname">{item.SUB_TITLE}</div>
                        </li>
                    ))}
                </ul>
            </div>
        </section>
    )
}

export default About;
