// vue3-slh/src/components/Home/HomeAbout.vue
<script setup>
import { ref, onMounted } from 'vue'
import axios from 'axios'
import { useIntersectionObserver } from '../../plugins/useIntersectionObserver'

const { isVisible, target } = useIntersectionObserver()

const URL = "http://localhost:3001/apis/about"
const data = ref([])
const loading = ref(false)
const error = ref(null)

const fetchData = async () => {
    try {
        error.value = null
        loading.value = true

        const response = await axios.get(URL)
        data.value = response.data.dataInfo.rows

    } catch(e) {
        error.value = e
    }
    loading.value = false
}

onMounted(() => {
    fetchData()
})

</script>

<template>
  <div ref="target">
    <section id="page02" class="section" :class="{ view: isVisible }">
        <div class="wrap">
            <div class="component">
                <div class="maintext">About</div>
                <span>" 사람을 위한 실용적인 기술을 만드는 소프트랩 흄 입니다. "</span>
            </div>

            <ul class="grid">
                <li v-for="(item, index) in data" :key="index">
                    <img :src="item.ICON" alt="" />
                    <div class="name">{{ item.TITLE }}</div>
                    <div class="subname">{{ item.SUB_TITLE }}</div>
                </li>
            </ul>
        </div>
    </section>
  </div>
</template>

<style scoped>

</style>

// react-slh/src/components/HomeAbout.jsx
import React, {useState, useEffect} from "react";
import { useIntersectionObserver } from "../IntersectionObserverContext";
import axios from 'axios';

function About() {
    const {ref, inView } = useIntersectionObserver();
    const URL =
    "http://localhost:3001/apis/about";
    // About 소개글 조회

    const [data, setData] = useState([]);
    const [loding, setLoding] = useState([]);
    const [error, setError] = useState([]);

    const fetchData = async () => {
        try {
            setError(null);
            setLoding(true);

            const response = await axios.get(URL);
            // console.log(response.data);
            // 응답 데이터 확인, 전체 출력
            // 확인완료 주석처리 2024-10-08, 10:26
            setData(response.data.dataInfo.rows);

        } catch(e) {
            setError(e);
        }
        setLoding(false);
    };
    useEffect(() => {
        fetchData();
    }, []);



    return(
        <section id="page02" className={`section ${inView ? 'view' : ''}`} ref={ref}>
            <div className="wrap">
                <div className="component">
                    <div className="maintext">About</div>
                    <span>" 사람을 위한 실용적인 기술을 만드는 소프트랩 흄 입니다. "</span>
                </div>

                <ul className="grid">
                    {data && data.map((item, index) => (
                        <li key={index}>
                            <img src={item.ICON} alt="" />
                            <div className="name">{item.TITLE}</div>
                            <div className="subname">{item.SUB_TITLE}</div>
                        </li>
                    ))}
                </ul>
            </div>
        </section>
    )
}

export default About;
